### PR TITLE
Add SVG push support and excluding favicons

### PR DESCRIPTION
**Pull request by multiwebinc**
SVG is a common image type used on the web and would also benefit from being pushed from the server.

### CODE REVIEW

**Comment by multiwebinc** [comment]
This should work for both `` or `<object data="algerie.svg">`.

**Review by JacobBennett — CHANGES_REQUESTED** [review]
Can you please write a test to verify this works correctly? Thank you for the contribution!

**Comment by multiwebinc** [comment]
Test works for me. I'm not sure if you want any additional tests. If so, let me know

```
$ ./vendor/bin/phpunit vendor/jacobbennett/laravel-http2serverpush/tests/AddHttp2ServerPushTest.php 
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

..........                                                        10 / 10 (100%)

Time: 597 ms, Memory: 6.00MB

OK (10 tests, 21 assertions)
```

**Comment by multiwebinc** [comment]
@JacobBennett ping

**Review by JacobBennett — APPROVED** [review]

**Comment by JacobBennett** [comment]
Perfect! Thanks so much, this looks great!

**Pull request merged**
