### PR TITLE
Config file for : Size limit, exceptions, base path

### PR DESCRIPTION
**Pull request by Nuranto**
solves #23 and #27

### CODE REVIEW

**Comment by JacobBennett** [comment]
Can you edit the `travis.yml` to not test 5.6 so that the tests will pass. Then we can make a new release that will only include PHP > 7

**Comment by Nuranto** [comment]
Ok, i removed 5.6, and added PHP 7.2 and 7.3 !

**Comment by Nuranto** [comment]
up :)

**Comment by Nuranto** [comment]
@JacobBennett  ? :)

**Review by vsg24 — APPROVED** [review]

**Comment by JacobBennett** [comment]
Hey guys, sorry about forever long wait on this. I'm sure you've probably moved on since :) I rarely look at this thing anymore. If anyone would like to write up new documentation for the readme, feel free.

**Comment by JacobBennett** [comment]
released on `v3.0.0`

**Pull request merged**
